### ISSUE TITLE
PyPI package has Python 2 classifier, but it cannot run on Python 2 due to Python 3 syntax

### ISSUE THREAD

**Issue by justanr** [fabfuel/circuitbreaker#1]
Specifically there are Python 3 type annotations being used.

**Comment by spatrik** [comment]
I noticed this as well, and tried to fix it. It's type annotations and that the exception ConnectionError (which is Python 3 only) is used in the tests that are the obvious issues. I can package this up as a PR, if there is interest in getting it to run on Python 2.

**Comment by fabfuel** [comment]
Hi @justanr & @spatrik,

first of all I'm sorry for classifying the project as Python 2 compatible on PyPI by mistake.
So far the project was not intended to be Python 2 compatible and so it was never tested with Python 2.

I'm happy to hear that other people are using the module and if there is a demand for using it on Python 2, I would be happy to merge a PR for creating Python 2 compatibility.

Best
Fabian

**Comment by justanr** [comment]
I'm interested, but after doing research for my particular use case, I'm not sure if a circuit breaker is feasible (web app running in uwsgi except each worker is a separate process ergo state isn't shared).

Unless there's further interest in Python 2 support, it is probably more appropriate to remove the trove classifier for Python 2.

**Comment by knil-sama** [comment]
@spatrik Hi, if you want to make it compatible to python2 I think the easiest way is to use mypy annotations
```
# This is how you annotate a function definition.
def stringify(num):
    # type: (int) -> str
    """Your function docstring goes here after the type definition."""
    return str(num)
```
If that is a acceptable solution to you I will gadly submit a PR for it.

**Comment by ofpiyush** [comment]
@fabfuel  One year later, it is still marked ok for python2.

**Comment by fabfuel** [comment]
The Python 2 classifier has been removed from PyPI package

**Comment by fabfuel** [comment]
With Version 1.1.0 (available on PyPI) the package now is fully Python 2 compatible. 
Thanks @TimDumol
