### ISSUE TITLE
Could you deploy the 1.3.1 version to the pypi?

### ISSUE THREAD

**Issue by ehdgua01** [fabfuel/circuitbreaker#15]
i suggest travis-ci's [pypi deployment](https://docs.travis-ci.com/user/deployment/pypi/)

**Comment by fabfuel** [comment]
Just pushed it to PyPI
https://pypi.org/project/circuitbreaker/

Best
Fabian

**Comment by fabfuel** [comment]
Thanks for the link, i'll check it out!
