### ISSUE TITLE
Is Python 3.8+ Supported by the Library?

### ISSUE THREAD

**Issue by github-anurag** [fabfuel/circuitbreaker#19]
Hi circuitbreaker users,

From the tox.ini, I can see that Python 3.7 is supported. Just wanted to make sure if Python 3.8+ is also supported or not.

Thanks,
Anurag Garg

**Comment by fabfuel** [comment]
Hi @github-anurag,

I just added the test configuration for Python 3.8 and Python 3.9 (see #20).
All passed, the library can be used with Python 3.8 and Python 3.9.

Best
Fabian
