### ISSUE TITLE
Should failure count reset outside of timeout?

### ISSUE THREAD

**Issue by matthewhughes934** [fabfuel/circuitbreaker#22]
I was wondering what the expected behaviour is when there are sequential failures, but they occur across more than one timeout period. For example timeout period is 30 seconds and failure threshold of 10: we fail 8 times, then a minute passes without our function called, then we fail 3 more times. Currently this will call a circuitbreaker to raise a `CircuitBreakerError` (see `test_current_failure_cooldown` below).

However it feels to me like the failure count should reset across timeout periods (see `test_suggested_failure_cooldown`).

```python
from datetime import datetime, timedelta

import pytest
from circuitbreaker import CircuitBreaker, CircuitBreakerError
from freezegun import freeze_time


class MyCircuitBreaker(CircuitBreaker):
    FAILURE_THRESHOLD = 10
    RECOVERY_TIMEOUT = 30


@MyCircuitBreaker()
def failing_func():
    raise ValueError()


def test_current_failure_cooldown():
    # we failed 8 times 2 minutes ago
    with freeze_time(datetime.now() - timedelta(minutes=2)):
        for _ in range(MyCircuitBreaker.FAILURE_THRESHOLD - 2):
            with pytest.raises(ValueError):
                failing_func()

    # then did nothing at all

    # then failing this minute...
    with freeze_time(datetime.now()):
        for _ in range(2):
            with pytest.raises(ValueError):
                failing_func()

        with pytest.raises(CircuitBreakerError):
            failing_func()

@pytest.mark.xfail()
def test_suggested_failure_cooldown():
    # we failed 8 times 2 minutes ago
    with freeze_time(datetime.now() - timedelta(minutes=2)):
        for _ in range(MyCircuitBreaker.FAILURE_THRESHOLD - 2):
            with pytest.raises(ValueError):
                failing_func()

    # then did nothing at all

    # then failing this minute...
    with freeze_time(datetime.now()):
        for _ in range(MyCircuitBreaker.FAILURE_THRESHOLD):
            with pytest.raises(ValueError):
                failing_func()

        with pytest.raises(CircuitBreakerError):
            failing_func() 
```

**Comment by fabfuel** [comment]
Hi Matthew,

thanks for sharing this question and the detailed example. Here is my opinion:

I'm afraid, this approach could render a circuit breaker implementation ineffective, as you might end up in a situation, where the integration point is unresponsive for a long period of time, but the circuit breaker never opens and is not able to fulfill its purpose.

Let's say we have a batch job, triggering 8 outgoing requests once a minute. A failure threshold of 10 and a timeout of 30 seconds. In this scenario, the circuit breaker would never open. 
It could never protect the integration point and not help the client to fail fast. Every minute again, the client would try to request data from the integration point, waiting for the timeout and - most importantly - imposing load on the integration point, not giving it time to recover. I believe this is the most important aspect of the timeout, stopping **all** requests, giving the integration point time to recover and then carefully switching to half-open state, sending only a single request to validate the availability.

What do you think?

Best
Fabian

**Comment by matthewhughes934** [comment]
Hi Fabin,

Thanks for the detailed response, as the timeout is just guarding how long before retrying on an open circuit should be attempted I definitely agree with your opinion.

My actual use case (that I probably should've started with) is in testing, something like:

```python
from datetime import datetime, timedelta

import pytest
from circuitbreaker import CircuitBreaker, CircuitBreakerError
from freezegun import freeze_time


class MyCircuitBreaker(CircuitBreaker):
    FAILURE_THRESHOLD = 10
    RECOVERY_TIMEOUT = 30


@MyCircuitBreaker()
def failing_func():
    raise ValueError()


def useful_function():
    try:
        failing_func()
    except ValueError:
        return -1
    except CircuitBreakerError:
        return -2
    else:
        return 0


# this test exists  just to verify our configuration
def test_failing_func_triggers_circuitbreaker_after_failures():
    expected_failure_threshold = 10

    # set the clock back several days to avoid interacting with other tests
    with freeze_time(datetime.now() - timedelta(days=4)):
        for _ in range(expected_failure_threshold):
            with pytest.raises(ValueError):
                failing_func()

        with pytest.raises(CircuitBreakerError):
            failing_func()


def test_useful_func_normal_return():
    # FAILURE: circuit is still open
    assert useful_function() == -2
```

The `test_useful_func_return` test will fail since the circuit is still open (even though the last request came through 4 days ago), though maybe `test_failing_func_triggers_circuitbreaker_after_failures` is redundant. 

However, for another use-case, imagine `failing_func` could be called by several different functions, and we want to test the error handling of each of those, we could accidentally start opening circuits just because we've added enough tests.
