### ISSUE TITLE
Add support for customizable failure logic

### ISSUE THREAD

**Issue by xtaje** [fabfuel/circuitbreaker#38]
There are cases where it's desirable to customize the logic around checking the thrown exception. (For example #23).

Another common example would be where a service is rate-limiting your API calls, and will inform you via HTTP code. In the requests library, this is only possible via inspecting the thrown HTTPError. In that example, you would want to circuit-break on the HTTPError only if it was 429, but not if it was 404 so that the client can fail fast.

**Comment by fabfuel** [comment]
#39 was merged, the feature will be part of the next release
