### ISSUE TITLE
Advanced usage with CircuitBreaker subclass is is broken

### ISSUE THREAD

**Issue by xtaje** [fabfuel/circuitbreaker#42]
PR #39 breaks existing users code if they have created a custom CircuitBreaker subclass as suggested in the `Advanced Usage` of the README file.

```
class MyCircuitBreaker(CircuitBreaker):
        FAILURE_THRESHOLD = 10
        RECOVERY_TIMEOUT = 60
        EXPECTED_EXCEPTION = RequestException
```

The CircuitBreaker class no longer uses the `EXPECTED_EXCEPTION` field. So if someone upgrades to the updated version of the library with #39, and uses this pattern, their custom circuitbreaker will trigger a failure with any `Exception` instead of `RequestException`.

I need to think for a bit to see if there's an easy non-breaking fix. Otherwise we would have to add a note in the changelog.

**Comment by fabfuel** [comment]
Fixed with #43
