### ISSUE TITLE
Unable to install with pip: `note: This is an issue with the package [...], not pip.`

### ISSUE THREAD

**Issue by mborsetti** [fabfuel/circuitbreaker#46]
I am getting this error when following the installation instructions. It says `note: This is an issue with the package [...], not pip.`:

```
$ pip install circuitbreaker
Collecting circuitbreaker
  Using cached circuitbreaker-1.3.2.tar.gz (7.9 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [12 lines of output]
      /usr/local/lib/python3.9/dist-packages/setuptools/_distutils/dist.py:275: UserWarning: Unknown distribution option: 'include_package_data'
        warnings.warn(msg)
      /usr/local/lib/python3.9/dist-packages/setuptools/_distutils/dist.py:275: UserWarning: Unknown distribution option: 'zip_safe'
        warnings.warn(msg)
      /usr/local/lib/python3.9/dist-packages/setuptools/_distutils/dist.py:275: UserWarning: Unknown distribution option: 'install_requires'
        warnings.warn(msg)
      usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
         or: setup.py --help [cmd1 cmd2 ...]
         or: setup.py --help-commands
         or: setup.py cmd --help

      error: invalid command 'egg_info'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by fabfuel** [comment]
Hi, I'm not able to reproduce this. Did you try to install in a clean virtual environment?

Best
Fabian

**Comment by mborsetti** [comment]
@fabfuel Thanks for the prompt response and for pointing me to the right direction.  Indeed something was corrupted in the local install, probably of `setuptools`, and a reinstall eventually fixed it.

Thanks you lots!

**Comment by YesSteve** [comment]
Hello, @fabfuel 
I am too facing the same issue as @mborsetti.
And I
![● import virtualenv • Untitled-2 - 13  Chapter 13 - Visual Studio Code 01-01-2023 14_26_55](https://user-images.githubusercontent.com/121685059/210165688-3bd91add-c9b0-4be2-9e6c-991e5f9eaee0.png)
 am trying to install pygame module in python via command: pip install pygame
I saw your comment on his issue and I too tried to create a virtual environment but still the problem continues
Please, tell me if you have any other solution to this problem
you can comment here or e-mail me at:  ### **danavearyan@gmail.com**    /    aryansdanave123@gmail.com
My profile name is Aryan.
Thank you!!!
