### ISSUE TITLE
Create new release

### ISSUE THREAD

**Issue by imredobos** [fabfuel/circuitbreaker#47]
I would like to make use of the failure predicate function in my code, it is only possible if I use the master or commit as a ref when I define the dependencies - which is kinda ugly. A new release (probably 1.4.0) would be appreciated.

**Comment by fabfuel** [comment]
Version 1.4.0 has been released on GitHub and PyPI. Please see more details here
https://github.com/fabfuel/circuitbreaker/releases/tag/1.4.0

Best Fabian
