### ISSUE TITLE
Possibility to add a fallback call instead of raise CircuitBreakerError

### ISSUE THREAD

**Issue by luiscoms** [fabfuel/circuitbreaker#5]
It could add a parameter like 

```python
def fallback_function():
  return True

@circuit(fallback=fallback_function)
def external_call():
    ...
```

So, when circuit is open, the fallback function is called instead of raise CircuitBreakerError

**Comment by fabfuel** [comment]
Interesting idea, sounds like a useful addition!

**Comment by duilio92** [comment]
@fabfuel are you accepting collaborations? I would like to try and solve this issue

**Comment by fabfuel** [comment]
Hi @duilio92, sure please go ahead!

**Comment by duilio92** [comment]
Cool, thanks! I will post the pull request once I complete it

**Comment by duilio92** [comment]
Pull request for this issue: https://github.com/fabfuel/circuitbreaker/pull/9 Please let me know if you have any comments or think something should be different, thanks!

**Comment by sumeshdubey-squla** [comment]
I guess there's a slight problem with this. If we call the fallback function, it will still try to call the method.

**Comment by duilio92** [comment]
Hi I think that @sumeshdubey-squla comment is correct, my bad. @fabfuel I will fix if that is ok with you.

**Comment by fabfuel** [comment]
Good catch @sumeshdubey-squla, yes please go ahead @duilio92 
Thanks!

**Comment by duilio92** [comment]
Gonna leave the pull request here https://github.com/fabfuel/circuitbreaker/pull/13 comments are welcome.
