### ISSUE TITLE
Add universal wheel to setup.py

### ISSUE THREAD

**Issue by imredobos** [fabfuel/circuitbreaker#50]
If one wants to install the package to a specific platform (e.g. manylinux2014_x86_64), pip fails because it could not find matching distribution. Since this lib does not have any C API call, universal wheel supposed to be created by:
`setup(options={'bdist_wheel':{'universal':True}})
`
The result shold be something like: circuitbreaker-1.4.1-py3-none-any.whl

**Comment by fabfuel** [comment]
Hi Imre,

I currently only publish the sdist, no binary distribution at all, not universal. This is why it _should_ work on any platform.

You get an error when you try to install the package? How do you install it? Could you please share the error? 

Thanks a lot
Fabian

**Comment by imredobos** [comment]
Hi,

`pip3 install circuitbreaker==1.4.0` works fine
`pip3 install circuitbreaker==1.4.0 --platform==macosx_10_10_universal2 --only-binary=:all:` shows: `ERROR: Could not find a version that satisfies the requirement circuitbreaker==1.4.0 (from versions: 1.0.1, 1.1.0)
ERROR: No matching distribution found for circuitbreaker==1.4.0`
Also, removing the version endS up with: 
`pip3 install circuitbreaker --platform==macosx_10_10_universal2 --only-binary=:all:` and `Collecting circuitbreaker
  Downloading circuitbreaker-1.1.0-py3-none-any.whl (7.8 kB)
Collecting typing
  Downloading typing-3.7.4.1-py3-none-any.whl (25 kB)
Installing collected packages: typing, circuitbreaker
Successfully installed circuitbreaker-1.1.0 typing-3.7.4.1`

It can be seen on pypi.org, that 1.1.0 has built distribution: https://pypi.org/project/circuitbreaker/1.1.0/#files
But 1.4.0 does not: https://pypi.org/project/circuitbreaker/1.4.0/#files
