### ISSUE TITLE
fallback function is being called everytime

### ISSUE THREAD

**Issue by akash-nx** [fabfuel/circuitbreaker#52]
I have below sample code:
```
def f_back():
    print("in fallback")
    return "Fall back"


@circuit(fallback_function=f_back(), failure_threshold=1)
def demo_call():
    x = requests.get('http://www.google.com')
    print(x.status_code)
    return "Success"


if __name__ == "__main__":
    response = demo_call()
    print(response)
```

On running above code I get:
```
in fallback
200
Success
```

on successful external call also my f_back() function gets called, why is this? am I missing anything?

**Comment by fabfuel** [comment]
Hi akash-nx,

you are calling your fallback function on declaration. Just remove the parentheses after `f_back` in line 6:
```
@circuit(fallback_function=f_back(), failure_threshold=1)
```

You are welcome. 

Best,
Fabian

**Comment by akash-nx** [comment]
Thanks @fabfuel , with that change:

```
def f_back():
    print("in fallback")
    return "Fall back"


@circuit(fallback_function=f_back, failure_threshold=1)
def demo_call():
    x = requests.get('http://www.googless.com')
    print(x.status_code)
    return "Success"
```

should call fallback as given google url is invalid and print "in fallback" right? But its not printing anything on console

**Comment by fabfuel** [comment]
No, the circuit opens **after** the first failed call. Don't confuse the circuit breaker with a proper try catch block. Please read about the behavior [here](https://github.com/fabfuel/circuitbreaker#failure-threshold) and the pattern [here](https://martinfowler.com/bliki/CircuitBreaker.html).  
Try this:

```
import requests
from circuitbreaker import circuit


def f_back():
    print("in fallback")
    return "Fall back"


@circuit(fallback_function=f_back, failure_threshold=1)
def demo_call():
    x = requests.get('http://www.googless.com')
    print(x.status_code)
    return "Success"


if __name__ == "__main__":
    try:
        response = demo_call()
        print(response)
    except Exception as e:
        print('Error: ' + str(e))
    try:
        response = demo_call()
        print(response)
    except Exception as e:
        print('Error: ' + str(e))
```

**Comment by akash-nx** [comment]
Understand, thanks!
