### ISSUE TITLE
License Details in LICENSE.rst file

### ISSUE THREAD

**Issue by akash-nx** [fabfuel/circuitbreaker#54]
I can see that this library has BSD-3 license from here: https://pypi.org/project/circuitbreaker/

<img width="366" alt="Screenshot 2022-11-09 at 11 25 41 AM" src="https://user-images.githubusercontent.com/82334485/200750445-bd14ab8a-56ee-4a73-9f44-2b70e6c4cc9d.png">

why the same is not mentioned in https://github.com/fabfuel/circuitbreaker/blob/master/LICENSE.rst ?

**Comment by fabfuel** [comment]
The license text is a BSD-3 License.
